### PR TITLE
Brutus Barks and some bug fixes

### LINKED ISSUE #318: Can talk to NPCs through walls
Add a raycast to the interactive radius so that you can't interact with things behind objects. Maybe have this functionality be turned off or on incase we want certain interactables to be interacted through walls.

### PR DESCRIPTION
**Pull request by chadleytan**
Main Changes:
* Added barks for the Brutus office mission 
* Use raycasts on top of the interactable range to prevent being able to interact through walls and objects. 
    * Note: All interactables must have some sort of collider on the gameObject where the `Interactable.cs`` script component is attached. Without it, the player cannot interact with it (Added colliders on interactables that did not have them before)
    * Fixes: #318 
* Reactive Barks only happen when player is in all the same zones as the character barking
* Added idle barks to change to lunch time rush barks during the kitchen mission after the dentures have been collected

### CODE REVIEW

File: Assets/Dialogue/Barks/BrutusOfficeBarks/BrutusOfficeIdleBark 3.asset [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  m_CorrespondingSourceObject: {fileID: 0}
+  m_PrefabInstance: {fileID: 0}
+  m_PrefabAsset: {fileID: 0}
+  m_GameObject: {fileID: 0}
+  m_Enabled: 1
+  m_EditorHideFlags: 0
+  m_Script: {fileID: 11500000, guid: 3a4c60ef165185e4d9c0e38f4bee7913, type: 3}
+  m_Name: BrutusOfficeIdleBark 3
+  m_EditorClassIdentifier: 
+  line: Who dis?     Brutus    Hehehe
```
Comment (jurcaua) [inline Assets/Dialogue/Barks/BrutusOfficeBarks/BrutusOfficeIdleBark 3.asset]: I'm confused by this line LOL like why he's saying this in idle LOL (sounds like maybe at the most he would say this in the mirror or something)
also the "dis" seems too slangy, maybe we should keep it to regular speech / old-timey speech for the residents?

File: Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs [hunk 2]
```diff
@@ -107,6 +100,13 @@ private void ReactiveBark()
 
     private void StartBark(BarkEvent barkEvent)
     {
+        // Barks only play when character is in the same zone as the player
+        List<CameraZone> characterZones = RegionManager.Instance.GetCharacterCurrentZones(this.gameObject);
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Dialogue/NPCDialogue/NPCReactiveBark.cs]: nitpick but, i think we can just do `this.gameObject` -> `gameObject`

File: Assets/Scripts/Interactables/Interactable.cs [hunk 3]
```diff
@@ -20,8 +20,18 @@ public class Interactable : MonoBehaviour, IInteractable
     public delegate void OnInteractEventHandler(Interactable source);
     public event OnInteractEventHandler OnInteractEnd;
 
+    private void Awake()
+    {
+
+    }
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Interactable.cs]: can we remove this?

File: Assets/Scripts/Interactables/Interactable.cs [hunk 4]
```diff
@@ -20,8 +20,18 @@ public class Interactable : MonoBehaviour, IInteractable
...
+
     protected virtual void Start()
     {
+        if (gameObject.GetComponent<Collider>() == null)
+        {
+            Debug.LogError(gameObject.name + " must have a collider on it");
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Interactable.cs]: nitpick
```suggestion
            Debug.LogError($"{gameObject.name} must have a collider on it");
```

File: Assets/Scripts/Interactables/Interactable.cs [hunk 5]
```diff
@@ -20,8 +20,18 @@ public class Interactable : MonoBehaviour, IInteractable
...
     public event OnInteractEventHandler OnInteractEnd;
 
+    private void Awake()
+    {
+
+    }
+
     protected virtual void Start()
     {
+        if (gameObject.GetComponent<Collider>() == null)
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Interactable.cs]:
```suggestion
        if (!Utils.HasComponent<Collider>(this))
```

File: Assets/Scripts/Interactables/Interactable.cs [hunk 6]
```diff
@@ -33,6 +43,18 @@ protected virtual void Update()
 
             if (!interactableOn && withinInteractRadius)
             {
+                // Do a raycast to see if there is anything that is obstructing the object from the player
+                // Solves issue of being able to talk through a wall
+                RaycastHit hit;
+                if (Physics.Raycast(player.transform.position, (transform.position - player.transform.position),
+                    out hit, interactRadius))
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Interactable.cs]:
```suggestion
                if (Physics.Raycast(player.transform.position, (transform.position - player.transform.position),
                    out RaycastHit hit, interactRadius))
```

File: Assets/Scripts/Interactables/Interactable.cs [hunk 7]
```diff
@@ -33,6 +43,18 @@ protected virtual void Update()
...
+                {
+                    if (!hit.collider.gameObject.Equals(this.gameObject))
```
Comment (jurcaua) [inline Assets/Scripts/Interactables/Interactable.cs]: nitpick, `this.gameObject` -> `gameObject`

File: Assets/Scripts/Region/RegionManager.cs [hunk 8]
```diff
@@ -115,6 +115,11 @@ public bool IsInZone(GameObject trackedObject, CameraZone zone)
         return trackedObjectZones.ContainsKey(trackedObject) && trackedObjectZones[trackedObject].Contains(zone);
     }
 
+    public List<CameraZone> GetCharacterCurrentZones(GameObject gameObject)
+    {
+        return trackedObjectZones[gameObject];
```
Comment (jurcaua) [inline Assets/Scripts/Region/RegionManager.cs:121]: I'd do a check here to make sure the key exists, maybe returning null otherwise (empty list may be confused for a valid object that just happens to be in no zones, so having that distinction would be good)

**Review by jurcaua — CHANGES_REQUESTED** [review]
NICE STUFF MY MAN
barks are SWEET 
brutus gonna look alive now
left some comments!!

File: Assets/Dialogue/Barks/BrutusOfficeBarks/BrutusOfficeIdleBark 3.asset (hunk 1 above)
Comment (chadleytan) [reply Assets/Dialogue/Barks/BrutusOfficeBarks/BrutusOfficeIdleBark 3.asset]: loooooooool couldnt come up with anything else but I'll change it

**Review by jurcaua — APPROVED** [review]
Looks all good to me now 😄 SPICK AND SPAN 👰

**Review by jurcaua — APPROVED** [review]
looks good to me man!!! great addition
